# Project Information
site_name: Prism.Container.Extensions
site_description: Documentation for the Prism Container Extensions
site_author: Dan Siegel
site_url: https://prismplugins.com

# Repository
repo_name: dansiegel/Prism.Container.Extensions
repo_url: https://github.com/dansiegel/Prism.Container.Extensions
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 Dan Siegel'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  logo: assets/prism-logo.png
  favicon: assets/favicon.ico
  language: en
  feature:
    tabs: true
  palette:
    primary: 'white'
    accent: 'cyan'

# Social
extra:
  social:
    - icon: fontawesome/brands/html5
      link: https://dansiegel.net
    - icon: fontawesome/brands/github
      link: https://github.com/dansiegel
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/dansiegel
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DanJSiegel
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/DanSiegel
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/DanSiegel

# Extensions
markdown_extensions:
  - admonition:
  - codehilite:
      linenums: false
  - toc:
      permalink: true

nav:
  - Prism:
    - Prism Library: http://prismlibrary.github.io/docs
  - Logging:
    - Logging: http://logging.prismplugins.com
  - Popups:
    - Popups: http://popups.prismplugins.com
  - Container Extensions:
    - Getting Started: index.md
    - RegisterMany: registermany.md
    - Delegate Registration: registerdelegates.md
    - Scoped Services: scoping.md
    - Registration with IServiceCollection: registerservices.md
    - Containers:
      - Basics: containers/index.md
      - DryIoc: containers/dryioc.md
      - Microsoft D.I. Extensions: containers/microsoft-extensions-dependencyinjection.md
      - Unity: containers/unity.md
    - Prism.Forms Extended:
      - Intro: forms/index.md
      - Page Behavior Factory: forms/pagebehaviorfactory.md
      - Global Navigation Errors: forms/navigationerrors.md
      - Fluent Navigation: forms/fluent-navigation.md
      - ExecutionAwareCommand: forms/executionawarecommand.md
    - Shiny Support:
      - Intro: shiny/index.md
      - Startup: shiny/startup.md
      - Modularity: shiny/modularity.md
      - Navigation: shiny/navigation.md
  - Mobile.BuildTools:
    - Mobile.BuildTools: http://mobilebuildtools.com

#google_analytics: UA-153405647-1